#!/usr/bin/env python3
import sys

def rstrip(s):
	while s and (s[-1] == '\r' or s[-1] == '\n'): s = s[:-1]
	return s

fa, fb = open(sys.argv[2]), open(sys.argv[3])

PE = True
WA = False
while True:
	la, lb = fa.readline(), fb.readline()
	if la:
		if not lb or la.strip() != lb.strip():
			WA = True
			quit(1)
		else:
			if not lb or rstrip(la) != rstrip(lb):
				PE = True
	elif lb:
		quit(1)
	else:
		break
if PE == True:
	quit(512)
