#!/usr/bin/env python3
import sys

def rstrip(s):
	while s and (s[-1] == '\r' or s[-1] == '\n'): s = s[:-1]
	return s

fa, fb = open(sys.argv[2], "rb"), open(sys.argv[3], "rb")
while True:
	la, lb = fa.readline(), fb.readline()
	if la:
		if not lb or la != lb: quit(1)
	elif lb:
		quit(1)
	else:
		break
