#include <stdio.h>
#include <string.h>
#include <stdlib.h>

typedef char Word[105];

int isChangable(Word dict, Word word){
  int error = 0;
    int length = strlen(word);
      for( int i = 0 ; i < length ; i++ ){
          if( dict[i] != word[i] ){
                error++;
                    }
                      }
                        
                          return error == 1;
                          }

                          int isAddable(Word dict, Word word){
                            int addCount = 0;
                              int length = strlen(word);
                                int dictLength = strlen(dict);
                                  int i, j;
                                    for( i = 0, j = 0 ; i < length && j < dictLength ; i++, j++ ){
                                        if( word[i] != dict[j] ){
                                              j--;
                                                    addCount++;
                                                        }
                                                          }
                                                            addCount += length - i;
                                                              return addCount == 1;
                                                              }


                                                              int main(){
                                                                Word *dictionary = (Word *)malloc(sizeof(Word) * 100005);
                                                                  
                                                                    int n;
                                                                      scanf("%d", &n);
                                                                        for( int i = 0 ; i < n ; i++ ){
                                                                            scanf("%s", dictionary[i]);
                                                                              }
                                                                                
                                                                                  int query_num;
                                                                                    Word query;
                                                                                      scanf("%d", &query_num);
                                                                                        for( int i = 0 ; i < query_num ; i++ ){
                                                                                            scanf("%s", query);
                                                                                                
                                                                                                    int isFind = 0;
                                                                                                        for( int j = 0 ; j < n ; j++ ){
                                                                                                              if( strcmp(dictionary[j], query) == 0 ){
                                                                                                                      printf(">%s\n", query);
                                                                                                                              isFind = 1;
                                                                                                                                      break;
                                                                                                                                            }
                                                                                                                                                }
                                                                                                                                                    
                                                                                                                                                        if( !isFind ){
                                                                                                                                                              int isCandidate = 0;
                                                                                                                                                                    int length = strlen(query);
                                                                                                                                                                          for( int j = 0 ; j < n ; j++ ){
                                                                                                                                                                                  int needPrint = 0;
                                                                                                                                                                                          int dictLength = strlen(dictionary[j]);
                                                                                                                                                                                                  if( dictLength == length ){
                                                                                                                                                                                                            if( isChangable(dictionary[j], query) ){
                                                                                                                                                                                                                        needPrint = 1;
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                  else if( dictLength - 1  == length ){
                                                                                                                                                                                                                                                            if( isAddable(query, dictionary[j]) ){
                                                                                                                                                                                                                                                                        needPrint = 1;
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                  else if( dictLength  == length - 1 ){
                                                                                                                                                                                                                                                                                                            if( isAddable(dictionary[j], query) ){
                                                                                                                                                                                                                                                                                                                        needPrint = 1;
                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                  else {
                                                                                                                                                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    if( needPrint ){
                                                                                                                                                                                                                                                                                                                                                                                              if( !isCandidate ){
                                                                                                                                                                                                                                                                                                                                                                                                          printf("?");
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                              else {
                                                                                                                                                                                                                                                                                                                                                                                                                                          printf(" ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("%s", dictionary[j]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isCandidate = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if( !isCandidate ){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              printf("!%s\n", query);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  printf("\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      free(dictionary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

